### ISSUE TITLE
no ssl on site

### ISSUE THREAD

**Issue by flo-dhalluin** [Polo2/Mariage-Polodile#71]
firefox fait plein de warning parcqu'on envoie un mot de passe sur une connexion non chiffrée. Moi ça me rend tout nerveux ...  

Si le site est bien hébergé sur heroku, tu peux activer facilement (et gratos) ssl avec : 
https://blog.heroku.com/announcing-automated-certificate-management

**Comment by Polo2** [comment]
bonjour Flo,
J'ai décidément hâte que nous fassions connaissance ! 
Merci pour le 1er message sur des données à retirer, 
 --> pris en compte dans la dernière PR, mais effectivement, il en reste 70 à nettoyer .. j'imagine qu'on peut faire mieux qu'à la main
et la demande de passage en ssl. 
 --> Je pense que la manip ne passe pas avec heroku , acr je n'ai pas payé de dyno pour faire ce projet. Mais tu es maintenant le 2e à me parler du ssl, je vais en installer un .. bientôt.
A bientôt donc !

**Comment by flo-dhalluin** [comment]
Hello, 

ça n'est pas aussi simple que ça ... : 
https://help.github.com/articles/removing-sensitive-data-from-a-repository/
Je me disais aussi que c'était trop beau pour être gratos heroku ... 
à bientôt !

**Comment by Polo2** [comment]
données sensibles retirées du repo github, merci , et
à bientôt donc !
